version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - docker login -u yokeshwer -p yokesh@docker
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.us-east-1.amazonaws.com
      - WP_URI=$ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/wordpress
      - echo "Docker Hub login successful."
      - echo "Amazon ECR login successful."
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image for WP..."
      - docker build -t $WP_URI:latest .
      - echo "Tagging Docker image for WP..."
      - docker tag $WP_URI:latest $WP_URI:latest
          
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker WP image..."
      - docker push $WP_URI:latest
    
